export const notificationsLog = [
    {
        id: 'nn*J3dBzQVa*JWCJO1dJkA',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: 'dMSN2wb8TC22Uxz5OuUlOg',
            name: 'Demo',
            firstName: 'Demo',
            logo: '/api/avatars/24/D.svg?v=2',
            gender: 'FEMALE',
            isActive: true,
            key: {
                id: 'dMSN2wb8TC22Uxz5OuUlOg',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'PRAISE_MENTIONED_YOU',
        module: 'MESSAGE',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: 'q9tRbJofR0S-414nbICgWg',
        data: null,
        createdAt: 1500641188761,
        visitedAt: 1500641608086,
    },
    {
        id: 'B03YLo9FTr6eEhO*oUXnTg',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: 'dMSN2wb8TC22Uxz5OuUlOg',
            name: 'Demo',
            firstName: 'Demo',
            logo: '/api/avatars/24/D.svg?v=2',
            gender: 'FEMALE',
            isActive: true,
            key: {
                id: 'dMSN2wb8TC22Uxz5OuUlOg',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'FEEDBACK_REQUESTED',
        module: 'FEEDBACK',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: 'yE-lwSchSmCnZtrC3FDLTQ',
        data: null,
        createdAt: 1500544658578,
        visitedAt: 1500544757189,
    },
    {
        id: 'vZ9vsOqwQteCqdNBF6L5LQ',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: 'E6YSzJtxR*SeBOsOxWwkdg',
            name: 'Maria the Manager',
            firstName: 'Maria',
            logo: '/images/characters/mary.svg',
            gender: 'FEMALE',
            isActive: true,
            key: {
                id: 'E6YSzJtxR*SeBOsOxWwkdg',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'REVIEW_SHARED_WITH_MANAGER',
        module: 'REVIEW',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: 'Q8kO9BjVTvi133a1LyZqPw',
        data: null,
        createdAt: 1500447147616,
        visitedAt: null,
    },
    {
        id: 'vr53TWszTa6B5dNp8YJGQQ',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: 'oghqoy1vS2WTILXczTVZzQ',
            name: 'Henry the HR',
            firstName: 'Henry',
            logo: '/api/avatars/1/HH.svg?v=2',
            gender: 'FEMALE',
            isActive: true,
            key: {
                id: 'oghqoy1vS2WTILXczTVZzQ',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'REVIEW_SHARED_WITH_MANAGER',
        module: 'REVIEW',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: 'OE1ugwLeSEm*6XrOw-3iRg',
        data: null,
        createdAt: 1500447147295,
        visitedAt: null,
    },
    {
        id: 'vwJEkvkpQF*LbmDZ1Z01dQ',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: 'S5*bmJJNRi2DwXHGic1Lbg',
            name: 'Thibault yet another HR',
            firstName: 'Thibault',
            logo: '/api/avatars/27/TH.svg?v=2',
            gender: 'FEMALE',
            isActive: true,
            key: {
                id: 'S5*bmJJNRi2DwXHGic1Lbg',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'REVIEW_SHARED_WITH_MANAGER',
        module: 'REVIEW',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: 'M46q3qSQTFGZU7WFH97NJA',
        data: null,
        createdAt: 1500447147182,
        visitedAt: null,
    },
    {
        id: 'jWUYudOnQumleg8KoQhyww',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: 'AO-brafhTfKfxRIfgX6hiA',
            name: 'Mark the Manager',
            firstName: 'Mark',
            logo: '/images/characters/toby.svg',
            gender: 'MALE',
            isActive: true,
            key: {
                id: 'AO-brafhTfKfxRIfgX6hiA',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'REVIEW_SHARED_WITH_MANAGER',
        module: 'REVIEW',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: 'LuX2HAzbRM2mV-Pktz5tVQ',
        data: null,
        createdAt: 1500447147030,
        visitedAt: null,
    },
    {
        id: 'bkFeOfxjQZSNiL74V0D-VQ',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: '0s1IVi91RsyrWwIXgt-d5g',
            name: 'Claude another HR',
            firstName: 'Claude',
            logo: '/api/avatars/26/CH.svg?v=2',
            gender: 'FEMALE',
            isActive: true,
            key: {
                id: '0s1IVi91RsyrWwIXgt-d5g',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'REVIEW_SHARED_WITH_MANAGER',
        module: 'REVIEW',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: 'F6whtLUnRq6fLj1ptQ3JIA',
        data: null,
        createdAt: 1500447146641,
        visitedAt: null,
    },
    {
        id: 'KhhcJ01fTQiCtnCVkZJG-w',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: 'dMSN2wb8TC22Uxz5OuUlOg',
            name: 'Demo',
            firstName: 'Demo',
            logo: '/api/avatars/24/D.svg?v=2',
            gender: 'FEMALE',
            isActive: true,
            key: {
                id: 'dMSN2wb8TC22Uxz5OuUlOg',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'REVIEW_SHARED_WITH_MANAGER',
        module: 'REVIEW',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: '9EOPRi4XSCy2d-AiJFDCYw',
        data: null,
        createdAt: 1500447146340,
        visitedAt: null,
    },
    {
        id: 'qy-a3fnUTsWHjFme5Lroaw',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: 'dMSN2wb8TC22Uxz5OuUlOg',
            name: 'Demo',
            firstName: 'Demo',
            logo: '/api/avatars/24/D.svg?v=2',
            gender: 'FEMALE',
            isActive: true,
            key: {
                id: 'dMSN2wb8TC22Uxz5OuUlOg',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'REVIEW_SHARED_WITH_MANAGER',
        module: 'REVIEW',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: 'yjweprWYRAG3Q*DJB6MlZw',
        data: null,
        createdAt: 1500446558501,
        visitedAt: null,
    },
    {
        id: 'H7DyXOLzT-6Zl6Kf0ZLptQ',
        userId: '84tFLaQPQryhRB6jCS9ckA',
        actor: {
            id: '0s1IVi91RsyrWwIXgt-d5g',
            name: 'Claude another HR',
            firstName: 'Claude',
            logo: '/api/avatars/26/CH.svg?v=2',
            gender: 'FEMALE',
            isActive: true,
            key: {
                id: '0s1IVi91RsyrWwIXgt-d5g',
                ownerType: 'com.praisemanager.account.domain.User',
            },
        },
        otherActor: null,
        type: 'REVIEW_SHARED_WITH_MANAGER',
        module: 'REVIEW',
        repetitionCount: 0,
        additionalActorsCount: 0,
        aggregatedOverActors: false,
        aggregatedOverRepetition: false,
        entityId: 'vXw4*-ODTIiRgI-pyNYrTQ',
        data: null,
        createdAt: 1500446558048,
        visitedAt: null,
    },
];

export const mockComments = [
    {
        id: '0',
        content:
            "You really did a great job at preparing the recruitment drive and executing it. The invites were sent on time, the mini-website looked fabulous, our booth looked great (despite the lean budget) and it was in a perfect location. We managed to get 25 high quality resumes, and Mark be making an offer to Dan, a really smart junior developer. I'd love to see more events like these in the future. Nothing beats personal contact.",
        author: {
            authorName: 'Darth Vader',
            imageSource: require('../assets/images/dave.jpg'),
        },
        num_likes_this: 3,
    },
    {
        id: '1',
        content: 'Hear hear! Totally agree.',
        author: {
            authorName: 'Darth Vader',
            imageSource: require('../assets/images/dave.jpg'),
        },
        num_likes_this: 2,
    },
    {
        id: '2',
        content: 'Are you my father?',
        author: {
            authorName: 'Luke Skywalker',
            imageSource: require('../assets/images/dave.jpg'),
        },
        num_likes_this: 3,
    },
    {
        id: '3',
        content: "Help me next time, you're my only hope.",
        author: {
            authorName: 'Princess Leia',
            imageSource: require('../assets/images/dave.jpg'),
        },
        num_likes_this: 2,
    },
    {
        id: '4',
        content: 'Follow me next time.',
        author: {
            authorName: 'Darth Sidious',
            imageSource: require('../assets/images/dave.jpg'),
        },
        num_likes_this: 3,
    },
    {
        id: '5',
        content: 'Something something something dark side.',
        author: {
            authorName: 'Steve Palpatine',
            imageSource: require('../assets/images/dave.jpg'),
        },
        num_likes_this: 2,
    },
];

export const mockObjective = {
    id: '23',
    title: 'Campus Recruitment Drive',
    author: 'Luke Skywalker',
    cycleName: 'Objectives Q1, 2018',
};
